# %%

import torch

from sentence_transformers import SentenceTransformer


# %%
header_words = [
    "#",
    "amount",
    "amt",
    "available bal.",
    "available balance",
    "bal",
    "balance",
    "balance amt",
    "beneficiary",
    "cheque no.",
    "cheque no/ reference no",
    "cheque no/reference no",
    "cheque number",
    "cheque#",
    "cheque/ref",
    "cheque/ref.no.",
    "cheque/reference#",
    "chequeno.",
    "chq / ref no.",
    "chq / ref number",
    "chq no",
    "chq no/ref no",
    "chq-no",
    "chq.",
    "chq. no.",
    "chq./ref. number",
    "chq./ref.no.",
    "chq./req. number",
    "chq.no.",
    "chq/ref",
    "chq/ref no",
    "chq/ref.no",
    "closing bal",
    "closing balance",
    "completion time",
    "cr",
    "cr amount",
    "cr.",
    "cr/dr",
    "credit",
    "credit amt",
    "credit or debit",
    "credit/debit",
    "credits",
    "credits/debits",
    "cust ref no",
    "customer ref",
    "date",
    "date id",
    "date of transaction",
    "dealer name",
    "debit",
    "debit amt",
    "debit/credit",
    "debits",
    "deposit",
    "deposit amt.",
    "deposit(cr amount)",
    "deposit(cr)",
    "deposits",
    "desc",
    "description",
    "details",
    "details of transaction",
    "dr",
    "dr / cr",
    "dr amount",
    "dr.",
    "entry date",
    "inst no",
    "inst number",
    "instr no",
    "instr. no.",
    "instrmnt number",
    "instrument id",
    "instrument no",
    "instrument number",
    "instruments",
    "name",
    "narration",
    "narrative",
    "no.",
    "paid in",
    "particulars",
    "party",
    "payee",
    "payment",
    "payment date",
    "post date",
    "receipt",
    "receipt no",
    "recipient",
    "ref",
    "ref no",
    "ref no./cheque no.",
    "ref num",
    "ref. no",
    "ref.no",
    "reference",
    "remarks",
    "running balance",
    "s.no",
    "serial",
    "serial number",
    "sl. no.",
    "sr no",
    "sr.no.",
    "srl",
    "srno",
    "total amount",
    "total amount dr/cr",
    "tran date",
    "tran id",
    "trans date",
    "trans dt",
    "transaction amount",
    "transaction credit amount",
    "transaction date",
    "transaction debit amount",
    "transaction description",
    "transaction details",
    "transaction id",
    "transaction type",
    "trn dt",
    "trn. date",
    "txn date",
    "txn type",
    "type",
    "utr",
    "utr number",
    "val date",
    "value",
    "value date",
    "value dt",
    "withdraw(dr amount)",
    "withdrawal",
    "withdrawal (dr)/deposit (cr)",
    "withdrawal amt.",
    "withdrawals",
    "withdrawl(dr)",
    "withdrawn",
]

# %%
header_model = SentenceTransformer("all-MiniLM-L6-v2")
HEADER_EMBEDDINGS = header_model.encode(header_words, convert_to_tensor=True)
